version: "3.9"

services:
  test:
    build:
      context: ./tests        
      dockerfile: Dockerfile
    environment:
      - ROBOT_BROWSER_HEADLESS=True
    volumes:
      - ./tests/output:/app/output   
    command: robot --outputdir /app/output *.robot
