version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    environment:
      - BACKEND_PORT=${BACKEND_PORT:-8000}
      - ENV=development
      - PINATA_API_KEY=${PINATA_API_KEY}
      - PINATA_SECRET_API_KEY=${PINATA_SECRET_API_KEY}
      - CACHE_DIR=/app/cache
    volumes:
      - ./backend/cache:/app/cache

  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT:-3000}
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:8000}
