apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prediction-app
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: prediction
  source:
    repoURL: https://github.com/JasvendraSingh/Prediction-App
    targetRevision: cicd
    path: helm/prediction-app
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true