name: Prediction-App Build & Deploy

on:
  push:
    branches: [main]

env:
  BACKEND_IMAGE: ghcr.io/jasvendrasingh/prediction-backend:latest
  FRONTEND_IMAGE: ghcr.io/jasvendrasingh/prediction-frontend:latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build & Push Backend
      - name: Build & push backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ env.BACKEND_IMAGE }}

      # Build & Push Frontend
      - name: Build & push frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ env.FRONTEND_IMAGE }}

      # Deploy to Codespaces
      - name: Deploy backend container
        run: |
          docker rm -f prediction_backend || true
          docker run -d \
            --name prediction_backend \
            -p 8000:8000 \
            -e PINATA_API_KEY=${{ secrets.PINATA_API_KEY }} \
            -e PINATA_SECRET_API_KEY=${{ secrets.PINATA_SECRET_API_KEY }} \
            ${{ env.BACKEND_IMAGE }}

      - name: Deploy frontend container
        run: |
          docker rm -f prediction_frontend || true
          docker run -d \
            --name prediction_frontend \
            -p 3000:80 \
            ${{ env.FRONTEND_IMAGE }}
