name: Docker Build & Push

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      build_all:
        description: "Force rebuild all images (ignore change detection)"
        required: false
        default: "false"

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine changed folders
        id: changes
        run: |
          echo "CHANGED_FRONTEND=false" >> $GITHUB_ENV
          echo "CHANGED_BACKEND=false" >> $GITHUB_ENV
          echo "CHANGED_TESTS=false" >> $GITHUB_ENV

          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ "${{ github.event.inputs.build_all }}" = "true" ]; then
            echo "Manual trigger with build_all=true → building everything"
            echo "CHANGED_FRONTEND=true" >> $GITHUB_ENV
            echo "CHANGED_BACKEND=true" >> $GITHUB_ENV
            echo "CHANGED_TESTS=true" >> $GITHUB_ENV
            exit 0
          fi

          git fetch --depth=2
          CHANGED=$(git diff --name-only HEAD^ HEAD || echo "")
          echo "Changed files:"
          echo "$CHANGED"

          if echo "$CHANGED" | grep -q '^frontend/'; then
            echo "CHANGED_FRONTEND=true" >> $GITHUB_ENV
          fi
          if echo "$CHANGED" | grep -q '^backend/'; then
            echo "CHANGED_BACKEND=true" >> $GITHUB_ENV
          fi
          if echo "$CHANGED" | grep -q '^tests/'; then
            echo "CHANGED_TESTS=true" >> $GITHUB_ENV
          fi

      - name: Debug changed values
        run: |
          echo "Frontend changed: $CHANGED_FRONTEND"
          echo "Backend changed: $CHANGED_BACKEND"
          echo "Tests changed: $CHANGED_TESTS"

      - name: Build and push frontend
        if: ${{ env.CHANGED_FRONTEND == 'true' }}
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.sha }}

      - name: Build and push backend
        if: ${{ env.CHANGED_BACKEND == 'true' }}
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }}

      - name: Build and push tests
        if: ${{ env.CHANGED_TESTS == 'true' }}
        uses: docker/build-push-action@v5
        with:
          context: ./tests
          file: ./tests/Dockerf
